/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminsRouteImport } from './routes/_authenticated.admins'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated.analytics'
import { Route as AuthenticatedAuditLogsRouteImport } from './routes/_authenticated.audit-logs'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated.notifications'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated.reports'
import { Route as AuthenticatedSellersRouteImport } from './routes/_authenticated.sellers'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedWishlistRouteImport } from './routes/_authenticated.wishlist'
import { Route as AuthenticatedFinanceExpenseHistoryRouteImport } from './routes/_authenticated.finance.expense-history'
import { Route as AuthenticatedFinanceExpensesRouteImport } from './routes/_authenticated.finance.expenses'
import { Route as AuthenticatedFinanceFundingHistoryRouteImport } from './routes/_authenticated.finance.funding-history'
import { Route as AuthenticatedFinanceInvestmentRouteImport } from './routes/_authenticated.finance.investment'
import { Route as AuthenticatedFinanceInvestorProfitRouteImport } from './routes/_authenticated.finance.investor-profit'
import { Route as AuthenticatedFinanceInvestorsRouteImport } from './routes/_authenticated.finance.investors'
import { Route as AuthenticatedFinanceLoanRepaymentsRouteImport } from './routes/_authenticated.finance.loan-repayments'
import { Route as AuthenticatedFinanceLoansRouteImport } from './routes/_authenticated.finance.loans'
import { Route as AuthenticatedFinanceProfitRouteImport } from './routes/_authenticated.finance.profit'
import { Route as AuthenticatedFinanceRemainingFundsRouteImport } from './routes/_authenticated.finance.remaining-funds'
import { Route as AuthenticatedFinanceRevenueRouteImport } from './routes/_authenticated.finance.revenue'
import { Route as AuthenticatedFinanceSimulatorRouteImport } from './routes/_authenticated.finance.simulator'
import { Route as AuthenticatedInventoryBrandsRouteImport } from './routes/_authenticated.inventory.brands'
import { Route as AuthenticatedInventoryCategoriesRouteImport } from './routes/_authenticated.inventory.categories'
import { Route as AuthenticatedInventoryProductsRouteImport } from './routes/_authenticated.inventory.products'
import { Route as AuthenticatedInventoryStockRouteImport } from './routes/_authenticated.inventory.stock'
import { Route as AuthenticatedInventoryStockAdjustmentRouteImport } from './routes/_authenticated.inventory.stock-adjustment'
import { Route as AuthenticatedOrdersIndexRouteImport } from './routes/_authenticated.orders.index'
import { Route as AuthenticatedOrdersDeliveriesRouteImport } from './routes/_authenticated.orders.deliveries'
import { Route as AuthenticatedOrdersPreOrdersRouteImport } from './routes/_authenticated.orders.pre-orders'
import { Route as AuthenticatedOrdersReturnsRouteImport } from './routes/_authenticated.orders.returns'
import { Route as AuthenticatedPurchasesHistoryRouteImport } from './routes/_authenticated.purchases.history'
import { Route as AuthenticatedPurchasesOrdersRouteImport } from './routes/_authenticated.purchases.orders'
import { Route as AuthenticatedPurchasesSuppliersRouteImport } from './routes/_authenticated.purchases.suppliers'
import { Route as AuthenticatedInvoiceTypeIdRouteImport } from './routes/_authenticated.invoice.$type.$id'
import { Route as AuthenticatedLabelOrderIdRouteImport } from './routes/_authenticated.label.order.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminsRoute = AuthenticatedAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAuditLogsRoute = AuthenticatedAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSellersRoute = AuthenticatedSellersRouteImport.update({
  id: '/sellers',
  path: '/sellers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWishlistRoute = AuthenticatedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceExpenseHistoryRoute =
  AuthenticatedFinanceExpenseHistoryRouteImport.update({
    id: '/finance/expense-history',
    path: '/finance/expense-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceExpensesRoute =
  AuthenticatedFinanceExpensesRouteImport.update({
    id: '/finance/expenses',
    path: '/finance/expenses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceFundingHistoryRoute =
  AuthenticatedFinanceFundingHistoryRouteImport.update({
    id: '/finance/funding-history',
    path: '/finance/funding-history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceInvestmentRoute =
  AuthenticatedFinanceInvestmentRouteImport.update({
    id: '/finance/investment',
    path: '/finance/investment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceInvestorProfitRoute =
  AuthenticatedFinanceInvestorProfitRouteImport.update({
    id: '/finance/investor-profit',
    path: '/finance/investor-profit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceInvestorsRoute =
  AuthenticatedFinanceInvestorsRouteImport.update({
    id: '/finance/investors',
    path: '/finance/investors',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceLoanRepaymentsRoute =
  AuthenticatedFinanceLoanRepaymentsRouteImport.update({
    id: '/finance/loan-repayments',
    path: '/finance/loan-repayments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceLoansRoute =
  AuthenticatedFinanceLoansRouteImport.update({
    id: '/finance/loans',
    path: '/finance/loans',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceProfitRoute =
  AuthenticatedFinanceProfitRouteImport.update({
    id: '/finance/profit',
    path: '/finance/profit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceRemainingFundsRoute =
  AuthenticatedFinanceRemainingFundsRouteImport.update({
    id: '/finance/remaining-funds',
    path: '/finance/remaining-funds',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceRevenueRoute =
  AuthenticatedFinanceRevenueRouteImport.update({
    id: '/finance/revenue',
    path: '/finance/revenue',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinanceSimulatorRoute =
  AuthenticatedFinanceSimulatorRouteImport.update({
    id: '/finance/simulator',
    path: '/finance/simulator',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryBrandsRoute =
  AuthenticatedInventoryBrandsRouteImport.update({
    id: '/inventory/brands',
    path: '/inventory/brands',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryCategoriesRoute =
  AuthenticatedInventoryCategoriesRouteImport.update({
    id: '/inventory/categories',
    path: '/inventory/categories',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryProductsRoute =
  AuthenticatedInventoryProductsRouteImport.update({
    id: '/inventory/products',
    path: '/inventory/products',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryStockRoute =
  AuthenticatedInventoryStockRouteImport.update({
    id: '/inventory/stock',
    path: '/inventory/stock',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryStockAdjustmentRoute =
  AuthenticatedInventoryStockAdjustmentRouteImport.update({
    id: '/inventory/stock-adjustment',
    path: '/inventory/stock-adjustment',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersIndexRoute =
  AuthenticatedOrdersIndexRouteImport.update({
    id: '/orders/',
    path: '/orders/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersDeliveriesRoute =
  AuthenticatedOrdersDeliveriesRouteImport.update({
    id: '/orders/deliveries',
    path: '/orders/deliveries',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersPreOrdersRoute =
  AuthenticatedOrdersPreOrdersRouteImport.update({
    id: '/orders/pre-orders',
    path: '/orders/pre-orders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrdersReturnsRoute =
  AuthenticatedOrdersReturnsRouteImport.update({
    id: '/orders/returns',
    path: '/orders/returns',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasesHistoryRoute =
  AuthenticatedPurchasesHistoryRouteImport.update({
    id: '/purchases/history',
    path: '/purchases/history',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasesOrdersRoute =
  AuthenticatedPurchasesOrdersRouteImport.update({
    id: '/purchases/orders',
    path: '/purchases/orders',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPurchasesSuppliersRoute =
  AuthenticatedPurchasesSuppliersRouteImport.update({
    id: '/purchases/suppliers',
    path: '/purchases/suppliers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoiceTypeIdRoute =
  AuthenticatedInvoiceTypeIdRouteImport.update({
    id: '/invoice/$type/$id',
    path: '/invoice/$type/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLabelOrderIdRoute =
  AuthenticatedLabelOrderIdRouteImport.update({
    id: '/label/order/$id',
    path: '/label/order/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admins': typeof AuthenticatedAdminsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sellers': typeof AuthenticatedSellersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/finance/expense-history': typeof AuthenticatedFinanceExpenseHistoryRoute
  '/finance/expenses': typeof AuthenticatedFinanceExpensesRoute
  '/finance/funding-history': typeof AuthenticatedFinanceFundingHistoryRoute
  '/finance/investment': typeof AuthenticatedFinanceInvestmentRoute
  '/finance/investor-profit': typeof AuthenticatedFinanceInvestorProfitRoute
  '/finance/investors': typeof AuthenticatedFinanceInvestorsRoute
  '/finance/loan-repayments': typeof AuthenticatedFinanceLoanRepaymentsRoute
  '/finance/loans': typeof AuthenticatedFinanceLoansRoute
  '/finance/profit': typeof AuthenticatedFinanceProfitRoute
  '/finance/remaining-funds': typeof AuthenticatedFinanceRemainingFundsRoute
  '/finance/revenue': typeof AuthenticatedFinanceRevenueRoute
  '/finance/simulator': typeof AuthenticatedFinanceSimulatorRoute
  '/inventory/brands': typeof AuthenticatedInventoryBrandsRoute
  '/inventory/categories': typeof AuthenticatedInventoryCategoriesRoute
  '/inventory/products': typeof AuthenticatedInventoryProductsRoute
  '/inventory/stock': typeof AuthenticatedInventoryStockRoute
  '/inventory/stock-adjustment': typeof AuthenticatedInventoryStockAdjustmentRoute
  '/orders/deliveries': typeof AuthenticatedOrdersDeliveriesRoute
  '/orders/pre-orders': typeof AuthenticatedOrdersPreOrdersRoute
  '/orders/returns': typeof AuthenticatedOrdersReturnsRoute
  '/purchases/history': typeof AuthenticatedPurchasesHistoryRoute
  '/purchases/orders': typeof AuthenticatedPurchasesOrdersRoute
  '/purchases/suppliers': typeof AuthenticatedPurchasesSuppliersRoute
  '/orders/': typeof AuthenticatedOrdersIndexRoute
  '/invoice/$type/$id': typeof AuthenticatedInvoiceTypeIdRoute
  '/label/order/$id': typeof AuthenticatedLabelOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admins': typeof AuthenticatedAdminsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/sellers': typeof AuthenticatedSellersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/finance/expense-history': typeof AuthenticatedFinanceExpenseHistoryRoute
  '/finance/expenses': typeof AuthenticatedFinanceExpensesRoute
  '/finance/funding-history': typeof AuthenticatedFinanceFundingHistoryRoute
  '/finance/investment': typeof AuthenticatedFinanceInvestmentRoute
  '/finance/investor-profit': typeof AuthenticatedFinanceInvestorProfitRoute
  '/finance/investors': typeof AuthenticatedFinanceInvestorsRoute
  '/finance/loan-repayments': typeof AuthenticatedFinanceLoanRepaymentsRoute
  '/finance/loans': typeof AuthenticatedFinanceLoansRoute
  '/finance/profit': typeof AuthenticatedFinanceProfitRoute
  '/finance/remaining-funds': typeof AuthenticatedFinanceRemainingFundsRoute
  '/finance/revenue': typeof AuthenticatedFinanceRevenueRoute
  '/finance/simulator': typeof AuthenticatedFinanceSimulatorRoute
  '/inventory/brands': typeof AuthenticatedInventoryBrandsRoute
  '/inventory/categories': typeof AuthenticatedInventoryCategoriesRoute
  '/inventory/products': typeof AuthenticatedInventoryProductsRoute
  '/inventory/stock': typeof AuthenticatedInventoryStockRoute
  '/inventory/stock-adjustment': typeof AuthenticatedInventoryStockAdjustmentRoute
  '/orders/deliveries': typeof AuthenticatedOrdersDeliveriesRoute
  '/orders/pre-orders': typeof AuthenticatedOrdersPreOrdersRoute
  '/orders/returns': typeof AuthenticatedOrdersReturnsRoute
  '/purchases/history': typeof AuthenticatedPurchasesHistoryRoute
  '/purchases/orders': typeof AuthenticatedPurchasesOrdersRoute
  '/purchases/suppliers': typeof AuthenticatedPurchasesSuppliersRoute
  '/orders': typeof AuthenticatedOrdersIndexRoute
  '/invoice/$type/$id': typeof AuthenticatedInvoiceTypeIdRoute
  '/label/order/$id': typeof AuthenticatedLabelOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admins': typeof AuthenticatedAdminsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/audit-logs': typeof AuthenticatedAuditLogsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/sellers': typeof AuthenticatedSellersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/wishlist': typeof AuthenticatedWishlistRoute
  '/_authenticated/finance/expense-history': typeof AuthenticatedFinanceExpenseHistoryRoute
  '/_authenticated/finance/expenses': typeof AuthenticatedFinanceExpensesRoute
  '/_authenticated/finance/funding-history': typeof AuthenticatedFinanceFundingHistoryRoute
  '/_authenticated/finance/investment': typeof AuthenticatedFinanceInvestmentRoute
  '/_authenticated/finance/investor-profit': typeof AuthenticatedFinanceInvestorProfitRoute
  '/_authenticated/finance/investors': typeof AuthenticatedFinanceInvestorsRoute
  '/_authenticated/finance/loan-repayments': typeof AuthenticatedFinanceLoanRepaymentsRoute
  '/_authenticated/finance/loans': typeof AuthenticatedFinanceLoansRoute
  '/_authenticated/finance/profit': typeof AuthenticatedFinanceProfitRoute
  '/_authenticated/finance/remaining-funds': typeof AuthenticatedFinanceRemainingFundsRoute
  '/_authenticated/finance/revenue': typeof AuthenticatedFinanceRevenueRoute
  '/_authenticated/finance/simulator': typeof AuthenticatedFinanceSimulatorRoute
  '/_authenticated/inventory/brands': typeof AuthenticatedInventoryBrandsRoute
  '/_authenticated/inventory/categories': typeof AuthenticatedInventoryCategoriesRoute
  '/_authenticated/inventory/products': typeof AuthenticatedInventoryProductsRoute
  '/_authenticated/inventory/stock': typeof AuthenticatedInventoryStockRoute
  '/_authenticated/inventory/stock-adjustment': typeof AuthenticatedInventoryStockAdjustmentRoute
  '/_authenticated/orders/deliveries': typeof AuthenticatedOrdersDeliveriesRoute
  '/_authenticated/orders/pre-orders': typeof AuthenticatedOrdersPreOrdersRoute
  '/_authenticated/orders/returns': typeof AuthenticatedOrdersReturnsRoute
  '/_authenticated/purchases/history': typeof AuthenticatedPurchasesHistoryRoute
  '/_authenticated/purchases/orders': typeof AuthenticatedPurchasesOrdersRoute
  '/_authenticated/purchases/suppliers': typeof AuthenticatedPurchasesSuppliersRoute
  '/_authenticated/orders/': typeof AuthenticatedOrdersIndexRoute
  '/_authenticated/invoice/$type/$id': typeof AuthenticatedInvoiceTypeIdRoute
  '/_authenticated/label/order/$id': typeof AuthenticatedLabelOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admins'
    | '/analytics'
    | '/audit-logs'
    | '/dashboard'
    | '/notifications'
    | '/reports'
    | '/sellers'
    | '/settings'
    | '/wishlist'
    | '/finance/expense-history'
    | '/finance/expenses'
    | '/finance/funding-history'
    | '/finance/investment'
    | '/finance/investor-profit'
    | '/finance/investors'
    | '/finance/loan-repayments'
    | '/finance/loans'
    | '/finance/profit'
    | '/finance/remaining-funds'
    | '/finance/revenue'
    | '/finance/simulator'
    | '/inventory/brands'
    | '/inventory/categories'
    | '/inventory/products'
    | '/inventory/stock'
    | '/inventory/stock-adjustment'
    | '/orders/deliveries'
    | '/orders/pre-orders'
    | '/orders/returns'
    | '/purchases/history'
    | '/purchases/orders'
    | '/purchases/suppliers'
    | '/orders/'
    | '/invoice/$type/$id'
    | '/label/order/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admins'
    | '/analytics'
    | '/audit-logs'
    | '/dashboard'
    | '/notifications'
    | '/reports'
    | '/sellers'
    | '/settings'
    | '/wishlist'
    | '/finance/expense-history'
    | '/finance/expenses'
    | '/finance/funding-history'
    | '/finance/investment'
    | '/finance/investor-profit'
    | '/finance/investors'
    | '/finance/loan-repayments'
    | '/finance/loans'
    | '/finance/profit'
    | '/finance/remaining-funds'
    | '/finance/revenue'
    | '/finance/simulator'
    | '/inventory/brands'
    | '/inventory/categories'
    | '/inventory/products'
    | '/inventory/stock'
    | '/inventory/stock-adjustment'
    | '/orders/deliveries'
    | '/orders/pre-orders'
    | '/orders/returns'
    | '/purchases/history'
    | '/purchases/orders'
    | '/purchases/suppliers'
    | '/orders'
    | '/invoice/$type/$id'
    | '/label/order/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admins'
    | '/_authenticated/analytics'
    | '/_authenticated/audit-logs'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/reports'
    | '/_authenticated/sellers'
    | '/_authenticated/settings'
    | '/_authenticated/wishlist'
    | '/_authenticated/finance/expense-history'
    | '/_authenticated/finance/expenses'
    | '/_authenticated/finance/funding-history'
    | '/_authenticated/finance/investment'
    | '/_authenticated/finance/investor-profit'
    | '/_authenticated/finance/investors'
    | '/_authenticated/finance/loan-repayments'
    | '/_authenticated/finance/loans'
    | '/_authenticated/finance/profit'
    | '/_authenticated/finance/remaining-funds'
    | '/_authenticated/finance/revenue'
    | '/_authenticated/finance/simulator'
    | '/_authenticated/inventory/brands'
    | '/_authenticated/inventory/categories'
    | '/_authenticated/inventory/products'
    | '/_authenticated/inventory/stock'
    | '/_authenticated/inventory/stock-adjustment'
    | '/_authenticated/orders/deliveries'
    | '/_authenticated/orders/pre-orders'
    | '/_authenticated/orders/returns'
    | '/_authenticated/purchases/history'
    | '/_authenticated/purchases/orders'
    | '/_authenticated/purchases/suppliers'
    | '/_authenticated/orders/'
    | '/_authenticated/invoice/$type/$id'
    | '/_authenticated/label/order/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admins': {
      id: '/_authenticated/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AuthenticatedAdminsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit-logs': {
      id: '/_authenticated/audit-logs'
      path: '/audit-logs'
      fullPath: '/audit-logs'
      preLoaderRoute: typeof AuthenticatedAuditLogsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sellers': {
      id: '/_authenticated/sellers'
      path: '/sellers'
      fullPath: '/sellers'
      preLoaderRoute: typeof AuthenticatedSellersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/wishlist': {
      id: '/_authenticated/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AuthenticatedWishlistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/expense-history': {
      id: '/_authenticated/finance/expense-history'
      path: '/finance/expense-history'
      fullPath: '/finance/expense-history'
      preLoaderRoute: typeof AuthenticatedFinanceExpenseHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/expenses': {
      id: '/_authenticated/finance/expenses'
      path: '/finance/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof AuthenticatedFinanceExpensesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/funding-history': {
      id: '/_authenticated/finance/funding-history'
      path: '/finance/funding-history'
      fullPath: '/finance/funding-history'
      preLoaderRoute: typeof AuthenticatedFinanceFundingHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/investment': {
      id: '/_authenticated/finance/investment'
      path: '/finance/investment'
      fullPath: '/finance/investment'
      preLoaderRoute: typeof AuthenticatedFinanceInvestmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/investor-profit': {
      id: '/_authenticated/finance/investor-profit'
      path: '/finance/investor-profit'
      fullPath: '/finance/investor-profit'
      preLoaderRoute: typeof AuthenticatedFinanceInvestorProfitRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/investors': {
      id: '/_authenticated/finance/investors'
      path: '/finance/investors'
      fullPath: '/finance/investors'
      preLoaderRoute: typeof AuthenticatedFinanceInvestorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/loan-repayments': {
      id: '/_authenticated/finance/loan-repayments'
      path: '/finance/loan-repayments'
      fullPath: '/finance/loan-repayments'
      preLoaderRoute: typeof AuthenticatedFinanceLoanRepaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/loans': {
      id: '/_authenticated/finance/loans'
      path: '/finance/loans'
      fullPath: '/finance/loans'
      preLoaderRoute: typeof AuthenticatedFinanceLoansRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/profit': {
      id: '/_authenticated/finance/profit'
      path: '/finance/profit'
      fullPath: '/finance/profit'
      preLoaderRoute: typeof AuthenticatedFinanceProfitRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/remaining-funds': {
      id: '/_authenticated/finance/remaining-funds'
      path: '/finance/remaining-funds'
      fullPath: '/finance/remaining-funds'
      preLoaderRoute: typeof AuthenticatedFinanceRemainingFundsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/revenue': {
      id: '/_authenticated/finance/revenue'
      path: '/finance/revenue'
      fullPath: '/finance/revenue'
      preLoaderRoute: typeof AuthenticatedFinanceRevenueRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance/simulator': {
      id: '/_authenticated/finance/simulator'
      path: '/finance/simulator'
      fullPath: '/finance/simulator'
      preLoaderRoute: typeof AuthenticatedFinanceSimulatorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/brands': {
      id: '/_authenticated/inventory/brands'
      path: '/inventory/brands'
      fullPath: '/inventory/brands'
      preLoaderRoute: typeof AuthenticatedInventoryBrandsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/categories': {
      id: '/_authenticated/inventory/categories'
      path: '/inventory/categories'
      fullPath: '/inventory/categories'
      preLoaderRoute: typeof AuthenticatedInventoryCategoriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/products': {
      id: '/_authenticated/inventory/products'
      path: '/inventory/products'
      fullPath: '/inventory/products'
      preLoaderRoute: typeof AuthenticatedInventoryProductsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/stock': {
      id: '/_authenticated/inventory/stock'
      path: '/inventory/stock'
      fullPath: '/inventory/stock'
      preLoaderRoute: typeof AuthenticatedInventoryStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/stock-adjustment': {
      id: '/_authenticated/inventory/stock-adjustment'
      path: '/inventory/stock-adjustment'
      fullPath: '/inventory/stock-adjustment'
      preLoaderRoute: typeof AuthenticatedInventoryStockAdjustmentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/': {
      id: '/_authenticated/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AuthenticatedOrdersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/deliveries': {
      id: '/_authenticated/orders/deliveries'
      path: '/orders/deliveries'
      fullPath: '/orders/deliveries'
      preLoaderRoute: typeof AuthenticatedOrdersDeliveriesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/pre-orders': {
      id: '/_authenticated/orders/pre-orders'
      path: '/orders/pre-orders'
      fullPath: '/orders/pre-orders'
      preLoaderRoute: typeof AuthenticatedOrdersPreOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/orders/returns': {
      id: '/_authenticated/orders/returns'
      path: '/orders/returns'
      fullPath: '/orders/returns'
      preLoaderRoute: typeof AuthenticatedOrdersReturnsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/history': {
      id: '/_authenticated/purchases/history'
      path: '/purchases/history'
      fullPath: '/purchases/history'
      preLoaderRoute: typeof AuthenticatedPurchasesHistoryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/orders': {
      id: '/_authenticated/purchases/orders'
      path: '/purchases/orders'
      fullPath: '/purchases/orders'
      preLoaderRoute: typeof AuthenticatedPurchasesOrdersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/purchases/suppliers': {
      id: '/_authenticated/purchases/suppliers'
      path: '/purchases/suppliers'
      fullPath: '/purchases/suppliers'
      preLoaderRoute: typeof AuthenticatedPurchasesSuppliersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoice/$type/$id': {
      id: '/_authenticated/invoice/$type/$id'
      path: '/invoice/$type/$id'
      fullPath: '/invoice/$type/$id'
      preLoaderRoute: typeof AuthenticatedInvoiceTypeIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/label/order/$id': {
      id: '/_authenticated/label/order/$id'
      path: '/label/order/$id'
      fullPath: '/label/order/$id'
      preLoaderRoute: typeof AuthenticatedLabelOrderIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminsRoute: typeof AuthenticatedAdminsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAuditLogsRoute: typeof AuthenticatedAuditLogsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSellersRoute: typeof AuthenticatedSellersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedWishlistRoute: typeof AuthenticatedWishlistRoute
  AuthenticatedFinanceExpenseHistoryRoute: typeof AuthenticatedFinanceExpenseHistoryRoute
  AuthenticatedFinanceExpensesRoute: typeof AuthenticatedFinanceExpensesRoute
  AuthenticatedFinanceFundingHistoryRoute: typeof AuthenticatedFinanceFundingHistoryRoute
  AuthenticatedFinanceInvestmentRoute: typeof AuthenticatedFinanceInvestmentRoute
  AuthenticatedFinanceInvestorProfitRoute: typeof AuthenticatedFinanceInvestorProfitRoute
  AuthenticatedFinanceInvestorsRoute: typeof AuthenticatedFinanceInvestorsRoute
  AuthenticatedFinanceLoanRepaymentsRoute: typeof AuthenticatedFinanceLoanRepaymentsRoute
  AuthenticatedFinanceLoansRoute: typeof AuthenticatedFinanceLoansRoute
  AuthenticatedFinanceProfitRoute: typeof AuthenticatedFinanceProfitRoute
  AuthenticatedFinanceRemainingFundsRoute: typeof AuthenticatedFinanceRemainingFundsRoute
  AuthenticatedFinanceRevenueRoute: typeof AuthenticatedFinanceRevenueRoute
  AuthenticatedFinanceSimulatorRoute: typeof AuthenticatedFinanceSimulatorRoute
  AuthenticatedInventoryBrandsRoute: typeof AuthenticatedInventoryBrandsRoute
  AuthenticatedInventoryCategoriesRoute: typeof AuthenticatedInventoryCategoriesRoute
  AuthenticatedInventoryProductsRoute: typeof AuthenticatedInventoryProductsRoute
  AuthenticatedInventoryStockRoute: typeof AuthenticatedInventoryStockRoute
  AuthenticatedInventoryStockAdjustmentRoute: typeof AuthenticatedInventoryStockAdjustmentRoute
  AuthenticatedOrdersDeliveriesRoute: typeof AuthenticatedOrdersDeliveriesRoute
  AuthenticatedOrdersPreOrdersRoute: typeof AuthenticatedOrdersPreOrdersRoute
  AuthenticatedOrdersReturnsRoute: typeof AuthenticatedOrdersReturnsRoute
  AuthenticatedPurchasesHistoryRoute: typeof AuthenticatedPurchasesHistoryRoute
  AuthenticatedPurchasesOrdersRoute: typeof AuthenticatedPurchasesOrdersRoute
  AuthenticatedPurchasesSuppliersRoute: typeof AuthenticatedPurchasesSuppliersRoute
  AuthenticatedOrdersIndexRoute: typeof AuthenticatedOrdersIndexRoute
  AuthenticatedInvoiceTypeIdRoute: typeof AuthenticatedInvoiceTypeIdRoute
  AuthenticatedLabelOrderIdRoute: typeof AuthenticatedLabelOrderIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminsRoute: AuthenticatedAdminsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAuditLogsRoute: AuthenticatedAuditLogsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSellersRoute: AuthenticatedSellersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedWishlistRoute: AuthenticatedWishlistRoute,
  AuthenticatedFinanceExpenseHistoryRoute:
    AuthenticatedFinanceExpenseHistoryRoute,
  AuthenticatedFinanceExpensesRoute: AuthenticatedFinanceExpensesRoute,
  AuthenticatedFinanceFundingHistoryRoute:
    AuthenticatedFinanceFundingHistoryRoute,
  AuthenticatedFinanceInvestmentRoute: AuthenticatedFinanceInvestmentRoute,
  AuthenticatedFinanceInvestorProfitRoute:
    AuthenticatedFinanceInvestorProfitRoute,
  AuthenticatedFinanceInvestorsRoute: AuthenticatedFinanceInvestorsRoute,
  AuthenticatedFinanceLoanRepaymentsRoute:
    AuthenticatedFinanceLoanRepaymentsRoute,
  AuthenticatedFinanceLoansRoute: AuthenticatedFinanceLoansRoute,
  AuthenticatedFinanceProfitRoute: AuthenticatedFinanceProfitRoute,
  AuthenticatedFinanceRemainingFundsRoute:
    AuthenticatedFinanceRemainingFundsRoute,
  AuthenticatedFinanceRevenueRoute: AuthenticatedFinanceRevenueRoute,
  AuthenticatedFinanceSimulatorRoute: AuthenticatedFinanceSimulatorRoute,
  AuthenticatedInventoryBrandsRoute: AuthenticatedInventoryBrandsRoute,
  AuthenticatedInventoryCategoriesRoute: AuthenticatedInventoryCategoriesRoute,
  AuthenticatedInventoryProductsRoute: AuthenticatedInventoryProductsRoute,
  AuthenticatedInventoryStockRoute: AuthenticatedInventoryStockRoute,
  AuthenticatedInventoryStockAdjustmentRoute:
    AuthenticatedInventoryStockAdjustmentRoute,
  AuthenticatedOrdersDeliveriesRoute: AuthenticatedOrdersDeliveriesRoute,
  AuthenticatedOrdersPreOrdersRoute: AuthenticatedOrdersPreOrdersRoute,
  AuthenticatedOrdersReturnsRoute: AuthenticatedOrdersReturnsRoute,
  AuthenticatedPurchasesHistoryRoute: AuthenticatedPurchasesHistoryRoute,
  AuthenticatedPurchasesOrdersRoute: AuthenticatedPurchasesOrdersRoute,
  AuthenticatedPurchasesSuppliersRoute: AuthenticatedPurchasesSuppliersRoute,
  AuthenticatedOrdersIndexRoute: AuthenticatedOrdersIndexRoute,
  AuthenticatedInvoiceTypeIdRoute: AuthenticatedInvoiceTypeIdRoute,
  AuthenticatedLabelOrderIdRoute: AuthenticatedLabelOrderIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
